Volume_Mute::F1
^Volume_Mute::^F1
!Volume_Mute::!F1
^!Volume_Mute::^!F1
Volume_Down::F2
^Volume_Down::^F2
!Volume_Down::!F2
^!Volume_Down::^!F2
Volume_Up::F3
^Volume_Up::^F3
!Volume_Up::!F3
^!Volume_Up::^!F3
Media_Prev::F4
^Media_Prev::^F4
!Media_Prev::!F4
^!Media_Prev::^!F4
Media_Play_Pause::F5
^Media_Play_Pause::^F5
!Media_Play_Pause::!F5
^!Media_Play_Pause::^!F5
Media_Next::F6
^Media_Next::^F6
!Media_Next::!F6
^!Media_Next::^!F6
Browser_Back::F7
^Browser_Back::^F7
!Browser_Back::!F7
^!Browser_Back::^!F7
Browser_Home::F8
^Browser_Home::^F8
!Browser_Home::!F8
^!Browser_Home::^!F8
AppsKey::F9
^AppsKey::^F9
!AppsKey::!F9
^!AppsKey::^!F9