Volume_Mute::F1
^Volume_Mute::^F1
!Volume_Mute::!F1
^!Volume_Mute::^!F1
#Volume_Mute::Volume_Mute
Volume_Down::F2
^Volume_Down::^F2
!Volume_Down::!F2
^!Volume_Down::^!F2
#Volume_Down::Volume_Down
Volume_Up::F3
^Volume_Up::^F3
!Volume_Up::!F3
^!Volume_Up::^!F3
#Volume_Up::Volume_Up
Media_Prev::F4
^Media_Prev::^F4
!Media_Prev::!F4
^!Media_Prev::^!F4
#Media_Prev::Media_Prev
Media_Play_Pause::F5
^Media_Play_Pause::^F5
!Media_Play_Pause::!F5
^!Media_Play_Pause::^!F5
#Media_Play_Pause::Media_Play_Pause
Media_Next::F6
^Media_Next::^F6
!Media_Next::!F6
^!Media_Next::^!F6
#Media_Next::Media_Next
Browser_Back::F7
^Browser_Back::^F7
!Browser_Back::!F7
^!Browser_Back::^!F7
#Browser_Back::Browser_Back
Browser_Home::F8
^Browser_Home::^F8
!Browser_Home::!F8
^!Browser_Home::^!F8
#Browser_Home::Browser_Home
AppsKey::F9
^AppsKey::^F9
!AppsKey::!F9
^!AppsKey::^!F9
#AppsKey::AppsKey